### ISSUE TITLE
Is it possible to use same git repo for multiple collections?

### ISSUE THREAD

**Issue by EnriqueSoria** [riedeljan/insomnia-universal-git#10]
Is it possible to use same git repo for multiple collections?

**Comment by riedeljan** [comment]
Hi @EnriqueSoria!

Right now you can only sync whole workspaces, did you mean them?  If yes, you can simply set up the same remote Git for both collections and use different values for `configFileName`.

Support for syncing smaller chunks than workspaces isn't implemented yet. But feel free to open up a PR and contribute! :)
