### ISSUE TITLE
I can't setup the plugin on a private repository

### ISSUE THREAD

**Issue by JonathanLoscalzo** [riedeljan/insomnia-universal-git#12]
I've installed the plugin but I couldn't use it with gitlab page. 

_Can I use it with https://gitlab.com/?_ 

I don't know what is the error, or where I could see the log for figure it out. 

I've create a token with API scope, then I've try to setup de URL as `https://gitlab.com/<group or user>/<project-name>` as well `https://gitlab.com`, but it doesn't work. 

`OS: ubuntu 20.04`

**Comment by riedeljan** [comment]
Hi Jonathan,

https://gitlab.com should be sufficient. Can you make sure you put all other information in correctly?

There should also be an error log which you should be able to see in the Console-Tab under `View -> Toggle DevTools`.

**Comment by JonathanLoscalzo** [comment]
I'm looking [this](https://github.com/riedeljan/insomnia-universal-git/blob/66ab2265890a79482a0c59387939af0fd9441565/src/gitProviders/gitlab.ts#L36) and this lines.

- I think that loadBranches() should be invoke every time we modified the form, on handleChange. 
With that fix, I think that all will be solved, at least visually. What do you think @riedeljan ?

**Comment by riedeljan** [comment]
Thank you so much for all the detail first!

I'll debug a little this afternoon - haven't worked for insomnia for the last months and end up with other strange errors now. Will let you know as soon as I can tell more :)

**Comment by riedeljan** [comment]
Thank you so much for all the details!

I just started out with a fresh installation of insomnia as I didn't use it for the past months.
I tried pulling an existing - back then working - repository and ended up with the same `ref is empty` error as you did  - although a ref was provided in my case and branch autocompletion worked out as expected. 🤔 

I'll dig into it this evening - haven't read my own codebase for a few months now. Will let you know as soon as possible!

**Comment by riedeljan** [comment]
Did you try entering a workspace file name? The defaulting to `config.json` doesn't seem to work. Entering it manually solved my problems straight away.

**Comment by JonathanLoscalzo** [comment]
> Thank you so much for all the details!
> 
> I just started out with a fresh installation of insomnia as I didn't use it for the past months. I tried pulling an existing - back then working - repository and ended up with the same `ref is empty` error as you did - although a ref was provided in my case and branch autocompletion worked out as expected. thinking
> 
> I'll dig into it this evening - haven't read my own codebase for a few months now. Will let you know as soon as possible!

I think that you "hit" exactly when `loadBranches` starts. In my case, It was invoked and It won't be invoked any more due to the trigger (componentDidMount)


> Did you try entering a workspace file name? The defaulting to `config.json` doesn't seem to work. Entering it manually solved my problems straight away.

Yes, I've also tried that but it doesn't work. 

Do you test it out with a "private repo" ?

**Comment by riedeljan** [comment]
> Yes, I've also tried that but it doesn't work.
> Do you test it out with a "private repo" ?
> Maybe something change on gitlab, because any other "git-related" plugin doesn't work

Yep, I tried it with a private repo within an up to date private instance. Will test with gitlab.com too.

**Comment by riedeljan** [comment]
At some points the ref param gets messed up for me too - will fix this asap - but branches load without issues on a fresh private project on gitlab.com. 

Although I noted the main branch only showed in the API response after I created an empty `config.json` from within Gitlab.

**Comment by riedeljan** [comment]
Nice to hear!

Yeah, we've got multiple issues here. 
1. I already implemented a fix locally for the default configuration file name.
2. Up next I'll make sure the plugin handles responses for empty repos correctly.
3. Last but not least I'll fix the ref-mess.

Will probably all be done this evening, thank's for your help so far!

What exactly do you mean with support for multiple session? Maybe just open up a new ticket with your exact wishes, so we can have a separate conversation there. :)

**Comment by riedeljan** [comment]
Hi @JonathanLoscalzo!

First up, sorry, the last weeks became surprisingly busy. I just merged fixes for (hopefully ;)) all problems listed in my last comment and published to NPM. Insomnia Plugin-Hub update might take a few days as they seem to run it manually or so.. However feel free to install directly from NPM or build the plugin yourself.

I appreciate any feedback whether the fix works :)

**Comment by JonathanLoscalzo** [comment]
For me is working! :+1:
