### ISSUE TITLE
How to push an insomnia json under a directory to my repo?

### ISSUE THREAD

**Issue by temobgallardo** [riedeljan/insomnia-universal-git#15]
Hello guys,

Currently my insomnia json file is under a directory, e. g. /solution/source/tools/ 
and wonder how can I tell the plugin to look under that directory for my insomnia.json file?

I have tried setting the Workspace File Name:  
/solution/source/tools/insomnia-wspce.json
./solution/source/tools/insomnia-wspce.json
solution/source/tools/insomnia-wspce.json
\solution\source\tools\insomnia-wspce.json
.\solution\source\tools\insomnia-wspce.json
solution\source\tools\insomnia-wspce.json

but no luck so far, is it possible at this point to do so?

Thank you very much

**Comment by riedeljan** [comment]
Hi!

The "workspace file name" field is only intended to specify a custom file name under which your workspace will be stored in the remote repo.

The plugin should automagically be able to sync your workspace, once you've set up the rest.

Best,
Jan
